version: "3"
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.web
    ports:
      - "32000:3306"
    restart: always
    container_name: phrase-db
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: phrase-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile  
    container_name: phrase-nginx  
    ports:
      - "80:80"      
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network: