version: "3"
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: mysql
    ports:
      - "32000:3306"
    restart: always
    container_name: phrase-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: phrase-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile  
    container_name: phrase-nginx  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/privkey.pem      
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network: